name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Unzip deno bin
        run: unzip ./deno.zip

      - name: Publish package
        env:
          JSR_URL: https://deno-registry-staging.net
        run: ./deno publish --provenance
